### ISSUE TITLE
Doesn't handle 1/3 fractions

### ISSUE THREAD

**Issue by nateuni** [supertype-de/Blinker#5]
Currently Blinker doesn't handle 1/3 fractions

<img width="580" alt="Screen Shot 2022-04-21 at 9 21 57 pm" src="https://user-images.githubusercontent.com/405559/164447734-d971afe5-8b12-4f9b-b910-d2e259a2838d.png">

**Comment by supertype-de** [comment]
Added ⅓ as well as other known precomposed fractions ↉ ⅒ ⅑ ⅛ ⅐ ⅙ ⅕ ¼ ⅖ ⅔ ⅜ ⅗ ⅘ ⅝ ⅚ ⅞

**Comment by nateuni** [comment]
Thank you!!!
